### ISSUE TITLE
Training Corpus Help

### ISSUE THREAD

**Issue by stickyburn** [mukilk7/word-rnn#1]
Hey guys, thanks for such a useful model!
I was just wondering as to where my training data goes for the model ? I have a folder with about 140 text files, which I would like to be read and fed to the model. How can I achieve this ?
Thanks!

**Comment by stickyburn** [comment]
[New Update] I put all my text files in a folder and directed the train command with the flag '--input_file="./*.txt" ' and i'm assuming it should work; but my program cant find 'nltk' for training, which is already installed. I cannot find the file where I can specify a path to the installed folder of nltk, or another way to resolve this problem. Thanks!
[Previous Update]
So I understand that I can specify a file name with the .main.py command, but is there any way I could use all the files in a specified folder, or do I need to put all these files into one single file and use that instead?

**Comment by stickyburn** [comment]
I worked out the above problem by using python activated terminal and downloading punkt from nltk download. The model is on training successfully with the *.txt flag, I just hope that it reads all text files in the folder. Will close this once training is complete with all files 😀

**Comment by mukilk7** [comment]
The code doesn't support reading in a set of files using wildcard yet. It is probably using a default file (tiny shakespeare corpus defined in constants.py) to train the model instead of your files. I'd recommend that you concatenate all the text files in your input directory into a single file (i.e. cat input\*.txt > big_input_file.txt) and then feed it as a single file to the model.

**Comment by stickyburn** [comment]
Cool, now im running the model with a concatenated file. Is there any way I could see if the input file has been successfully loaded or not? I dont see anything on the console as such.
Thanks!

**Comment by stickyburn** [comment]
Soo the training was completed, but on generating the text words, I get an error saying : `
input_x = [vocab_to_idx[i] for i in starting_words]
KeyError: 'KING' `
Does this have to do something with the fact that my input text doesnt have any KING word at all ?
